### ISSUE TITLE
Optimize LogUtils

### ISSUE THREAD

**Issue by TwiN** [TwinProduction/TwinUtils#1]
- Remove init and instead use a static getInstance()
- If the logging file is set by using LogUtils.getInstance().setFileName(...), automatically log to file. Otherwise, don't.
- In doLog(...), currently checking if the file is too big before actually checking if we're even saving to a file! make sure to check if we're saving to a file before doing that

I guess I did indeed make that a while ago and I have improved since, but looking back at it, I forgot to use my head quite often back then

**Comment by TwinProduction** [comment]
Removed LogUtils, there's no point in reinventing the wheel. There's so much already existing good logging libraries, like SLF4J.
